In [8]:
%matplotlib inline
import matplotlib
import seaborn as sns
import numpy as np
matplotlib.rcParams['savefig.dpi'] = 144

# Pandas

Pandas là một thư viện phổ biến trong Python được sử dụng để làm việc với dữ liệu và phân tích dữ liệu. 
Loại dữ liệu chính của Pandas là các bảng dữ liệu (data frames), và chuỗi dữ liệu (Data series).
Các thao tác với dữ liệu  thể được sắp xếp, lọc, chọn, thêm mới dữ liệu và thực hiện nhiều thao tác khác trên dữ liệu.




In [9]:
import pandas as pd

In [10]:
?pd.DataFrame

**1. Tạo một data frame**

Để tạo một đối tượng dataframe trong Pandas, chúng ta có thể sử dụng hàm `pandas.DataFrame()`.

Các tham số của hàm này bao gồm dữ liệu (như một mảng NumPy hoặc một dictionary) và các tham số khác như tên các cột hoặc chỉ số của các dòng.

In [11]:
dict1 = {"id":[1,2,3,4,5], "name":["A", "B", "C", "D", "E"]}


In [12]:
df_dict = pd.DataFrame(dict1)
df_dict

id name
0   1    A
1   2    B
2   3    C
3   4    D
4   5    E

In [13]:
arr = np.arange(1,11).reshape(5,2)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [15]:
df_arr = pd.DataFrame(arr, columns = ["a","b"])
df_arr

a   b
0  1   2
1  3   4
2  5   6
3  7   8
4  9  10

**2. Các hàm đọc file trong Pandas**

Pandas hỗ trợ đọc các file định dạng khác nhau và trả về kiểu dữ liệu dataframe. Các hàm thực hiện gồm có:

`read_csv`: đọc dữ liệu từ một file có định dạng (extension) .csv và trả về một DataFrame.

`read_excel`: đọc dữ liệu từ một file Excel và trả về một DataFrame.

`read_json`: đọc dữ liệu từ một file JSON và trả về một DataFrame.

`read_sql`: đọc dữ liệu từ một cơ sở dữ liệu SQL và trả về một DataFrame.

In [18]:
# Tạo df từ numpy array
random_data = np.random.random((4,3))
print(random_data)
df_random = pd.DataFrame(random_data, columns=['a', 'b', 'c'])
df_random

[[0.70236376 0.13823574 0.27603778]
 [0.04276739 0.96902438 0.85819702]
 [0.45020778 0.61427441 0.55946504]
 [0.45059732 0.59588958 0.76498508]]


a         b         c
0  0.702364  0.138236  0.276038
1  0.042767  0.969024  0.858197
2  0.450208  0.614274  0.559465
3  0.450597  0.595890  0.764985

In [19]:
# Tạo DataFrame từ các dữ liệu dict of lists
d = {"col1": [1, 2,3,4], "col2": ["A","B", "X", "Y"]}
df_d = pd.DataFrame(data=d)
print(d, "\n", type(d) )
print(df_d, "\n", type(df_d))

{'col1': [1, 2, 3, 4], 'col2': ['A', 'B', 'X', 'Y']} 
 <class 'dict'>
   col1 col2
0     1    A
1     2    B
2     3    X
3     4    Y 
 <class 'pandas.core.frame.DataFrame'>


In [29]:
# Đọc từ file csv vào dataframe
df_csv = pd.read_csv("data/Salaries.csv")
# df_csv.head()
# df_csv.head(15)

# df_csv.tail()
# df_csv.tail(15)

# df_csv.size #1932502
# df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


**3. Một số hàm xem thông tin của Pandas DataFrame**

`dataframe.head()`: Hiển thị 5 dòng đầu tiên của bảng ghi; head(15) hiển thị 15 dòng đầu

`dataframe.tail(n)`: Trả về n dòng cuối cùng của dataframe.

`dataframe.shape`: Trả về tuple số dòng và số cột của dataframe.

`dataframe.size`: Kiểm tra kích thước của bảng ghi (số dòng x số cột)

`dataframe.columns`: Trả về danh sách tên cột của dataframe.

`dataframe.index`: Trả về chỉ số của các dòng của dataframe.

`dataframe.info()`: Hiển thị thông tin về dataframe, bao gồm số lượng giá trị không bị thiếu và kiểu dữ liệu của từng cột.

`dataframe.describe()`: Hiển thị thống kê mô tả cho dataframe, bao gồm số lượng, giá trị trung bình, độ lệch chuẩn, giá trị nhỏ nhất, giá trị lớn nhất và các giá trị percentiles.

 

In [30]:
# Hiển thị kích thước của dataframe
df_csv.shape #(148654, 13)

(148654, 13)

In [32]:
# Hiển thị danh sách tên cột của df
print(df_csv.columns) # Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay', 'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency','Status'], dtype='object')

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')


In [33]:
# hiển thị thông tin chi tiết các cột/columns của df
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [34]:
# Hiển thị các thống kê mô tả (đối với các cột dữ liệu số)cho df
df_csv.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**4. Một số thao tác xử lý dữ liệu trong dataframe**


*4.1. Truy cập phần tử của dataframe*

- Sử dụng dấu ngoặc vuông [] để truy cập vào một cột của DataFrame.  Vì `DataFrame` là `dict` của `Series`, nên chúng ta có thể chọn một cột và sau đó chọn một hàng bằng cách sử dụng ký hiệu dấu ngoặc vuông, chứ không phải ngược lại 

- `dataframe.loc`: Truy cập một nhóm các hàng và cột theo (các) nhãn hoặc một mảng boolean. Cú pháp: `dataframe.loc[row_labels][column_labels]` hoặc`dataframe.loc[row_labels, column_labels]`

- `dataframe.iloc`: truy cập vào một nhóm các dòng và cột của DataFrame bằng index số. Cú pháp  `dataframe.iloc[row_index][column_index]`

In [36]:
# Hiển thị 10 dòng đầu của cột "Year"
df_csv['Year'].head(10)

0    2011
1    2011
2    2011
3    2011
4    2011
5    2011
6    2011
7    2011
8    2011
9    2011
Name: Year, dtype: int64

In [54]:
# Xem phần tử thứ/hàng 6 của cột "Year" 
df_csv['Year'][5]

2011

In [55]:
# Câu lệnh này không đúng
# df_csv[9]['name']

In [60]:
#  Truy cập phần tử ở hàng 101, cột "id"  bằng hàm loc[]
print(df_csv.loc[100, 'Id']) # 101

# Truy cập các phần tử ở 2 cột đầu tiên trong hàng đầu tiên (index=0)
print(df_csv.iloc[0][0:2])

101
Id                           1
EmployeeName    NATHANIEL FORD
Name: 0, dtype: object


*4.2 Các phép toán trên dataframe*

- Mỗi cột là 1 series tương đương 1 mảng numpy array 1 chiều. Do đó, các phép toán dùng cho numpy array đều dùng cho series trong pandas.

- Vì dataframe là kiểu `dict` của `series` nên các hàm toán học và thao tác với `dict` cũng được dùng trong df.

- Thao tác làm thay đổi kích thước DF: thêm, xóa hàng/cột, gộp nhiều DF.
    - Thêm cột vào vị trí cuối DF, ta chỉ cần gán giá trị cho một cột mới với tên cột tương ứng. Để thêm cột vào vị trí xác định, ta dùng hàm `dataframe.insert()`. Cú pháp: `df.insert(loc, column, value)`
    - Thêm hàng vào DF, ta dùng hàm `dataframe.append()`. 
    - Để xóa cột, hàng, ta dùng hàm `dataframe.drop()`.
    - Để hợp nhất nhiều DF ta dùng `dataframe.merge()`.
    

In [62]:
#Tạo 1 df gồm 10 đối tượng (entries)
df_user = pd.read_csv("data/Salaries.csv").iloc[:10]
print(df_user, "\n", df_user.shape)

   Id        EmployeeName                                        JobTitle  \
0   1      NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2        GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3      ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4   CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5     PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
5   6      DAVID SULLIVAN                       ASSISTANT DEPUTY CHIEF II   
6   7           ALSON LEE              BATTALION CHIEF, (FIRE DEPARTMENT)   
7   8       DAVID KUSHNER                  DEPUTY DIRECTOR OF INVESTMENTS   
8   9      MICHAEL MORRIS              BATTALION CHIEF, (FIRE DEPARTMENT)   
9  10  JOANNE HAYES-WHITE          CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.

In [67]:
# Thêm một cột thông tin về tuổi (age) với các giá trị từ list
age = [21, 25, 56, 33, 28, 26, 33, 29, 41, 20]
df_user["age"] = age
print(df_user)

   Id        EmployeeName                                        JobTitle  \
0   1      NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2        GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3      ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4   CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5     PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
5   6      DAVID SULLIVAN                       ASSISTANT DEPUTY CHIEF II   
6   7           ALSON LEE              BATTALION CHIEF, (FIRE DEPARTMENT)   
7   8       DAVID KUSHNER                  DEPUTY DIRECTOR OF INVESTMENTS   
8   9      MICHAEL MORRIS              BATTALION CHIEF, (FIRE DEPARTMENT)   
9  10  JOANNE HAYES-WHITE          CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.

In [68]:
df_user.drop("age", axis = 1, inplace= True)
df_user

Id        EmployeeName                                        JobTitle  \
0   1      NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2        GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3      ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4   CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5     PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
5   6      DAVID SULLIVAN                       ASSISTANT DEPUTY CHIEF II   
6   7           ALSON LEE              BATTALION CHIEF, (FIRE DEPARTMENT)   
7   8       DAVID KUSHNER                  DEPUTY DIRECTOR OF INVESTMENTS   
8   9      MICHAEL MORRIS              BATTALION CHIEF, (FIRE DEPARTMENT)   
9  10  JOANNE HAYES-WHITE          CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   
5  118602.00      8601.00  189082.74       NaN  316285.74         316285.74   
6   92492.01     89062.90  134426.14       NaN  315981.05         315981.05   
7  256576.96         0.00   51322.50       NaN  307899.46         307899.46   
8  176932.64     86362.68   40132.23       NaN  303427.55         303427.55   
9  285262.00         0.00   17115.73       NaN  302377.73         302377.73   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN  
5  2011    NaN  San Francisco     NaN  
6  2011    NaN  San Francisco     NaN  
7  2011    NaN  San Francisco     NaN  
8  2011    NaN  San Francisco     NaN  
9  2011    NaN  San Francisco     NaN

In [69]:
# Dùng hàm insert để thêm cột vào vị trí thứ 3
df_user.insert(2, "age", age) #insert(index, nameCol, arr)
df_user

Id        EmployeeName  age  \
0   1      NATHANIEL FORD   21   
1   2        GARY JIMENEZ   25   
2   3      ALBERT PARDINI   56   
3   4   CHRISTOPHER CHONG   33   
4   5     PATRICK GARDNER   28   
5   6      DAVID SULLIVAN   26   
6   7           ALSON LEE   33   
7   8       DAVID KUSHNER   29   
8   9      MICHAEL MORRIS   41   
9  10  JOANNE HAYES-WHITE   20   

                                         JobTitle    BasePay  OvertimePay  \
0  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.00   
1                 CAPTAIN III (POLICE DEPARTMENT)  155966.02    245131.88   
2                 CAPTAIN III (POLICE DEPARTMENT)  212739.13    106088.18   
3            WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00     56120.71   
4    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.00   
5                       ASSISTANT DEPUTY CHIEF II  118602.00      8601.00   
6              BATTALION CHIEF, (FIRE DEPARTMENT)   92492.01     89062.90   
7                  DEPUTY DIRECTOR OF INVESTMENTS  256576.96         0.00   
8              BATTALION CHIEF, (FIRE DEPARTMENT)  176932.64     86362.68   
9          CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)  285262.00         0.00   

    OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
0  400184.25       NaN  567595.43         567595.43  2011    NaN   
1  137811.38       NaN  538909.28         538909.28  2011    NaN   
2   16452.60       NaN  335279.91         335279.91  2011    NaN   
3  198306.90       NaN  332343.61         332343.61  2011    NaN   
4  182234.59       NaN  326373.19         326373.19  2011    NaN   
5  189082.74       NaN  316285.74         316285.74  2011    NaN   
6  134426.14       NaN  315981.05         315981.05  2011    NaN   
7   51322.50       NaN  307899.46         307899.46  2011    NaN   
8   40132.23       NaN  303427.55         303427.55  2011    NaN   
9   17115.73       NaN  302377.73         302377.73  2011    NaN   

          Agency  Status  
0  San Francisco     NaN  
1  San Francisco     NaN  
2  San Francisco     NaN  
3  San Francisco     NaN  
4  San Francisco     NaN  
5  San Francisco     NaN  
6  San Francisco     NaN  
7  San Francisco     NaN  
8  San Francisco     NaN  
9  San Francisco     NaN

In [70]:
# Xóa hàng thứ 3 của DF. 
df_user.drop(2)
df_user.shape

(10, 14)

Hàm `drop()` trong câu lệnh trên chỉ xóa tạm thời, và kết quả tạo ra 1 bản sao df mới được sửa đổi, df cũ không bị thay đổi. 

Hầu hết các thao tác trong Pandas trả về một bản sao của DataFrame, thay vì sửa đổi chính đối tượng DataFrame. Do đó, để thay đổi vĩnh viễn DataFrame, chúng ta cần gán lại biến df hoặc sử dụng từ khóa inplace.

Ví dụ, để xóa trực tiếp trong df hiện tại (df_user), truyền vào tham số `inplace= True`.


In [71]:
df_user.drop(2, inplace = True)
df_user.shape

(9, 14)

In [72]:
df_user

Id        EmployeeName  age  \
0   1      NATHANIEL FORD   21   
1   2        GARY JIMENEZ   25   
3   4   CHRISTOPHER CHONG   33   
4   5     PATRICK GARDNER   28   
5   6      DAVID SULLIVAN   26   
6   7           ALSON LEE   33   
7   8       DAVID KUSHNER   29   
8   9      MICHAEL MORRIS   41   
9  10  JOANNE HAYES-WHITE   20   

                                         JobTitle    BasePay  OvertimePay  \
0  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.00   
1                 CAPTAIN III (POLICE DEPARTMENT)  155966.02    245131.88   
3            WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00     56120.71   
4    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.00   
5                       ASSISTANT DEPUTY CHIEF II  118602.00      8601.00   
6              BATTALION CHIEF, (FIRE DEPARTMENT)   92492.01     89062.90   
7                  DEPUTY DIRECTOR OF INVESTMENTS  256576.96         0.00   
8              BATTALION CHIEF, (FIRE DEPARTMENT)  176932.64     86362.68   
9          CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)  285262.00         0.00   

    OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
0  400184.25       NaN  567595.43         567595.43  2011    NaN   
1  137811.38       NaN  538909.28         538909.28  2011    NaN   
3  198306.90       NaN  332343.61         332343.61  2011    NaN   
4  182234.59       NaN  326373.19         326373.19  2011    NaN   
5  189082.74       NaN  316285.74         316285.74  2011    NaN   
6  134426.14       NaN  315981.05         315981.05  2011    NaN   
7   51322.50       NaN  307899.46         307899.46  2011    NaN   
8   40132.23       NaN  303427.55         303427.55  2011    NaN   
9   17115.73       NaN  302377.73         302377.73  2011    NaN   

          Agency  Status  
0  San Francisco     NaN  
1  San Francisco     NaN  
3  San Francisco     NaN  
4  San Francisco     NaN  
5  San Francisco     NaN  
6  San Francisco     NaN  
7  San Francisco     NaN  
8  San Francisco     NaN  
9  San Francisco     NaN


Hàm `merge()` trong Pandas DataFrame được sử dụng để kết hợp (merge) hai hoặc nhiều DataFrame thành một DataFrame duy nhất dựa trên một hoặc nhiều cột chung (key).

`pd.merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=True, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)`

Trong đó:

- left và right là hai DataFrame cần kết hợp
- on, left_on và right_on là các cột chung được sử dụng để kết hợp các DataFrame. Nếu không được chỉ định, Pandas sẽ sử dụng tất cả các cột chung trong các DataFrame
- how xác định loại kết hợp được sử dụng, bao gồm 'inner' (giao của hai tập hợp), 'outer' (hợp của hai tập hợp), 'left' (tập hợp trái và các phần tử chung) và 'right' (tập hợp phải và các phần tử chung)
- left_index và right_index xác định xem liệu chỉ số của DataFrame nào có được sử dụng làm key
- sort xác định xem kết quả có được sắp xếp theo key không
- suffixes là tên đuôi để thêm vào các tên cột bị trùng lặp trong trường hợp kết hợp có các cột trùng tên
- indicator cho biết liệu kết quả có thêm cột _merge để chỉ ra cách mà các key được kết hợp hay không.


 Ví dụ, để kết hợp hai DataFrame "df_user" và "df2" theo cột chung "key", ta có thể sử dụng mã sau:



 

In [76]:
df2 = pd.read_csv("data/orders.csv")

print(df2.head())
print(df2.shape)

   id  customer_id  product_id delivery_country
0   0         1866         686            India
1   1         1921         617            China
2   1         1921          54          Armenia
3   1         1921         566            China
4   1         1921         128          Lebanon
(2000, 4)


# Lọc khung dữ liệu

Một trong những công cụ phân tích mạnh mẽ của Pandas DataFrame là cú pháp lọc dữ liệu của nó. Thông thường, chúng ta sẽ chỉ cần làm việc với một tập hợp con dữ liệu nhất định dựa trên một số tiêu chí.
Các hàm lọc dữ liệu như: 
- count(): đếm số lượng dữ liệu theo 1 tiêu chí cụ thể 
- unique(): liệt kê danh sách các giá trị khác nhau
- fillna(): phương thức fillna() để điền giá trị 0 vào các ô dữ liệu bị thiếu (NaN) của DataFrame  

In [108]:
# df2['delivery_country'].count() #2000
df2['delivery_country'].unique()
# df_user.loc[9, 'Notes'] = pd.Series(df_user.loc[9, 'Notes']).fillna(0).iloc[0]
# df_user.loc[9, 'Benefits'] = df_user.loc[9, 'Benefits'].fillna(0)
# df_user.loc[9, 'Notes'] = np.nan_to_num(df_user.loc[9, 'Notes'], 0)

# df_user.head()

array(['India', 'China', 'Armenia', 'Lebanon', 'Spain', 'Denmark',
       'Mexico', 'Finland', 'Burundi', 'France', 'Lithuania', 'Iceland',
       'USA', 'Germany', 'Angola', 'Italy', 'Senegal', 'Russia',
       'Vietnam', 'Guinea', 'Norway', 'Sweden', 'Mali', 'Qatar',
       'Ivory Coast', 'Macedonia', 'Slovakia', 'Rwanda', 'UK', 'Poland',
       'Tanzania', 'Canada', 'Japan', 'Benin', 'South Korea', 'Belarus',
       'Moxambique', 'Algeria', 'Latvia', 'Oman', 'Austria', 'Malawi',
       'Kuwait', 'Yemen', 'Albania', 'Madagascar', 'Egypt',
       'United Arab Emirates', 'Turkey', 'Ghana', 'South Africa',
       'Estonia', 'Chad', 'Hungry', 'Serbia', 'Tunisia', 'Kenya',
       'Azerbaijan', 'Czech Republic', 'Gabon', 'Mauritius', 'Georgia',
       'Ukraine', 'Zimbabwe', 'Moldova', 'Saudi Arabia', 'Namibia',
       'Cameroon', 'Morocco', 'Lesotho', 'Slovenia', 'Iraq', 'Niger',
       'Croatia', 'Montenegro', 'Botswana', 'Israel', 'Sierra Leon',
       'Nigeria', 'Bulgaria', 'Togo', 'Jor

In [104]:
# Lọc thông tin id và delivery_country của các order có product_id nhỏ hơn hoặc bằng 100
partial_df =  df2[df2['product_id'] <= 100][["id", "delivery_country"]]  
print(partial_df.head())
print(partial_df.shape)

    id delivery_country
2    1          Armenia
11   4           Mexico
30  12           Russia
38  15           Norway
45  19            Qatar
(209, 2)


How does this filtering work?

Khi viết `df['delivery_country'] == 'USA'`, Pandas chọn cột `'delivery_country'` và kiểm tra từng hàng xem có giá trị là `'USA'` hay không. Nếu đúng, hàng đó sẽ được đánh dấu `True`, ngược lại được đánh dấu là `False`. Hoạt động được thực hiện trên Pandas `Series`và trả về 1 Pandas `Series` các giá trị Boolean

In [105]:
print(df2[df2['delivery_country'] == 'USA'].head())

      id  customer_id  product_id delivery_country
22     7         1457         462              USA
190   86         1064         696              USA
287  141         1060         854              USA
288  141         1060         262              USA
289  141         1060         169              USA


In [107]:
# Đếm số đơn hàng được giao tới USA
(df2['delivery_country'] == 'USA').sum() #72

72

# Bài tập thực hành

Bài 1. Tạo 1 DataFrame tên 'df' từ mảng numpy array kích thước 20x5 các số nguyên có giá trị ngẫu nhiên từ 0 đến 20, với tên cột là ['c0','c1', 'c2'. 'c3', 'c4']. Hãy mô tả các thông số thống kê của 'df'. 

Bài 2. Thực hiện các thao tác sau với df:
    
    a. Hiển thị 4 entries đầu tiên và 2 entries cuối cùng của df
    b. Hiển thị 10 phần tử đầu tiên của cột "c1"
    c. Hiển thị 3 phần tử cuối cùng của cột "c1"
    d. Bổ sung 1 cột "c5" gồm dãy các số 10.
    e. Tìm phần tử có giá trị lớn nhất trong df.
    f. Xóa hàng thứ 5 và cột 'c1' của df.
 
Bài 3. Đọc file Salaries.csv vào dataframe tên df_salary và thực hiện các thao tác sau:

    a. Xem kích thước của df_salary
    b. Xem thông tin của df_salary
    c. Mô tả thống kê các thông tin của df_salary
    d. Xác định giá trị trung bình của trường thông tin lương cơ bản "BasePay"
    e. Tính tổng số tiền trả ngoài giờ "OvertimePay"
    f. Tìm tên của nhân viên có số tiền trả ngoài giờ "OvertimePay" cao nhất
    g. Tìm tên của nhân viên được trả lương "TotalPay" cao nhất
    h. Tìm nghề có mức lương cơ sở cao nhất.
    i. Có bao nhiêu nghề nghiệp trong bảng?
    j. Hãy thay thế các giá trị trống và thay thế bằng số 0.
    

In [ ]:
# Bài 1:

